--Req1
SELECT thph.ID_HOTEL,
       thph.ID_TIPO_HABITACION,
       thph.CANTIDAD_HABITACIONES_DISPONIBLES
FROM DA_TIPO_HABITACION_POR_HOTEL thph
LEFT JOIN DA_RESERVAS r
  ON thph.ID_HOTEL = r.ID_HOTEL
 AND thph.ID_TIPO_HABITACION = r.ID_TIPO_HABITACION
 AND NOT (
     r.FECHA_FINAL <= :FECHA_INICIO
     OR r.FECHA_INICIO >= :FECHA_FIN
 )
WHERE thph.ID_HOTEL = :ID_HOTEL
GROUP BY thph.ID_HOTEL, thph.ID_TIPO_HABITACION,
         thph.CANTIDAD_HABITACIONES_DISPONIBLES
HAVING thph.CANTIDAD_HABITACIONES_DISPONIBLES > COUNT(r.ID_RESERVA);