--Req2
SELECT c.NOMBRE_CIUDAD,
       h.NOMBRE,
       TRUNC(r.FECHA_INICIO, 'MM') AS MES,
       COUNT(*) AS TOTAL_RESERVAS
FROM DA_RESERVAS r
JOIN DA_HOTEL h ON r.ID_HOTEL = h.ID_HOTEL
JOIN DA_CIUDAD c ON h.ID_CIUDAD = c.ID_CIUDAD
WHERE r.FECHA_INICIO BETWEEN :FECHA_INICIO AND :FECHA_FIN
GROUP BY c.NOMBRE_CIUDAD, h.NOMBRE, TRUNC(r.FECHA_INICIO, 'MM')
ORDER BY MES;