--Req5
SELECT h.NOMBRE,
       COALESCE(scf.NOMBRE, scc.NOMBRE) AS SERVICIO,
       COUNT(*) AS VECES_USADO
FROM DA_RESERVA_SERVICIO rs
JOIN DA_RESERVAS r ON rs.ID_RESERVA = r.ID_RESERVA
JOIN DA_HOTEL h ON r.ID_HOTEL = h.ID_HOTEL
LEFT JOIN DA_SERVICIO_COSTO_FIJO scf 
       ON rs.ID_SERVICIO_FIJO = scf.ID_SERVICIO
LEFT JOIN DA_SERVICIO_COSTO_CONSUMO scc 
       ON rs.ID_SERVICIO_CONSUMO = scc.ID_SERVICIO
WHERE r.FECHA_INICIO BETWEEN :FECHA_INICIO AND :FECHA_FIN
GROUP BY h.NOMBRE, COALESCE(scf.NOMBRE, scc.NOMBRE)
ORDER BY VECES_USADO DESC;

SELECT h.NOMBRE,
       th.NOMBRE_TIPO,
       COUNT(*) AS VECES_RESERVADA
FROM DA_RESERVAS r
JOIN DA_HOTEL h ON r.ID_HOTEL = h.ID_HOTEL
JOIN DA_TIPO_HABITACION th 
     ON r.ID_TIPO_HABITACION = th.ID_TIPO_HABITACION
WHERE r.FECHA_INICIO BETWEEN :FECHA_INICIO AND :FECHA_FIN
GROUP BY h.NOMBRE, th.NOMBRE_TIPO
ORDER BY VECES_RESERVADA DESC;