--Req3
SELECT c.NOMBRE_CIUDAD,
       h.NOMBRE,
       r.FECHA_INICIO,
       SUM(r.ADULTOS + r.MENORES_3_ANIOS) AS TOTAL_HUESPEDES
FROM DA_RESERVAS r
JOIN DA_HOTEL h ON r.ID_HOTEL = h.ID_HOTEL
JOIN DA_CIUDAD c ON h.ID_CIUDAD = c.ID_CIUDAD
WHERE r.FECHA_INICIO BETWEEN :FECHA_INICIO AND :FECHA_FIN
GROUP BY c.NOMBRE_CIUDAD, h.NOMBRE, r.FECHA_INICIO;