-- ============================================================
-- ORDEN DE CREACION (respeta dependencias de FK):
--   1. DA_CIUDAD
--   2. DA_ADMINISTRADOR
--   3. DA_CLIENTE
--   4. DA_HOTEL
--   5. DA_TIPO_HABITACION
--   6. DA_TIPO_HABITACION_POR_HOTEL
--   7. DA_HABITACION
--   8. DA_SERVICIO_COSTO_FIJO
--   9. DA_SERVICIO_COSTO_CONSUMO
--  10. DA_HOTEL_TIPO_HAB_SERVICIO
--  11. DA_ADMINISTRADO_POR
--  12. DA_RESERVAS
--  13. DA_RESERVA_SERVICIO
-- ============================================================



BEGIN EXECUTE IMMEDIATE 'DROP TABLE DA_RESERVA_SERVICIO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DA_RESERVAS';                 EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DA_ADMINISTRADO_POR';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DA_HOTEL_TIPO_HAB_SERVICIO';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DA_SERVICIO_COSTO_CONSUMO';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DA_SERVICIO_COSTO_FIJO';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DA_HABITACION';               EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DA_TIPO_HABITACION_POR_HOTEL';EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DA_TIPO_HABITACION';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DA_HOTEL';                    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DA_CLIENTE';                  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DA_ADMINISTRADOR';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DA_CIUDAD';                   EXCEPTION WHEN OTHERS THEN NULL; END;
/



CREATE TABLE DA_CIUDAD (
    ID_CIUDAD     NUMBER        NOT NULL,
    NOMBRE_CIUDAD VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_DA_CIUDAD PRIMARY KEY (ID_CIUDAD)
);



CREATE TABLE DA_ADMINISTRADOR (
    DOCUMENTO_IDENTIDAD NUMBER        NOT NULL,
    NOMBRE              VARCHAR2(100) NOT NULL,
    APELLIDOS           VARCHAR2(100) NOT NULL,
    CORREO_ELECTRONICO  VARCHAR2(150) NOT NULL,
    TELEFONO            NUMBER        NOT NULL,
    CONSTRAINT PK_DA_ADMIN PRIMARY KEY (DOCUMENTO_IDENTIDAD)
);



CREATE TABLE DA_CLIENTE (
    DOCUMENTO_IDENTIDAD NUMBER        NOT NULL,
    NOMBRE              VARCHAR2(100) NOT NULL,
    APELLIDOS           VARCHAR2(100) NOT NULL,
    CORREO_ELECTRONICO  VARCHAR2(150) NOT NULL,
    TELEFONO            NUMBER        NOT NULL,
    CONSTRAINT PK_DA_CLIENTE PRIMARY KEY (DOCUMENTO_IDENTIDAD)
);




CREATE TABLE DA_HOTEL (
    ID_HOTEL            NUMBER        NOT NULL,
    NOMBRE              VARCHAR2(100) NOT NULL,
    DIRECCION           VARCHAR2(200) NOT NULL,
    TELEFONO            NUMBER,
    NUMERO_HABITACIONES NUMBER        NOT NULL,
    ID_CIUDAD           NUMBER        NOT NULL,
    CONSTRAINT PK_DA_HOTEL PRIMARY KEY (ID_HOTEL),
    CONSTRAINT FK_DA_HOTEL_CIUDAD
        FOREIGN KEY (ID_CIUDAD) REFERENCES DA_CIUDAD(ID_CIUDAD)
);



CREATE TABLE DA_TIPO_HABITACION (
    ID_TIPO_HABITACION     NUMBER        NOT NULL,
    NOMBRE_TIPO            VARCHAR2(100) NOT NULL,
    DIMENSIONES_HABITACION FLOAT         NOT NULL,
    TIPO_CAMAS             VARCHAR2(50)  NOT NULL,
    CANTIDAD_CAMAS         NUMBER        NOT NULL,
    TIPO_VISTA             VARCHAR2(50)  NOT NULL,
    COMODIDADES_HABITACION VARCHAR2(300) NOT NULL,
    PRECIO                 NUMBER        NOT NULL,
    CONSTRAINT PK_DA_TIPO_HAB PRIMARY KEY (ID_TIPO_HABITACION),
    CONSTRAINT CHK_DA_TIPO_CAMAS CHECK (
        TIPO_CAMAS IN ('King', 'Queen', 'Doble', 'Single')
    ),
    CONSTRAINT CHK_DA_TIPO_VISTA CHECK (
        TIPO_VISTA IN ('Al mar', 'A monumentos', 'A piscina', 'Estandar')
    ),
    CONSTRAINT CHK_DA_PRECIO_TH CHECK (PRECIO > 0)
);




CREATE TABLE DA_TIPO_HABITACION_POR_HOTEL (
    ID_HOTEL                          NUMBER NOT NULL,
    ID_TIPO_HABITACION                NUMBER NOT NULL,
    PRECIO_ALTA                       FLOAT  NOT NULL,
    PRECIO_BAJA                       FLOAT  NOT NULL,
    CANTIDAD_HABITACIONES_DISPONIBLES NUMBER NOT NULL,
    CONSTRAINT PK_DA_THPH
        PRIMARY KEY (ID_HOTEL, ID_TIPO_HABITACION),
    CONSTRAINT FK_DA_THPH_HOTEL
        FOREIGN KEY (ID_HOTEL) REFERENCES DA_HOTEL(ID_HOTEL),
    CONSTRAINT FK_DA_THPH_TIPO
        FOREIGN KEY (ID_TIPO_HABITACION) REFERENCES DA_TIPO_HABITACION(ID_TIPO_HABITACION),
    CONSTRAINT CHK_DA_PRECIO_ALTA  CHECK (PRECIO_ALTA > 0),
    CONSTRAINT CHK_DA_PRECIO_BAJA  CHECK (PRECIO_BAJA > 0),
    CONSTRAINT CHK_DA_CANT_HAB     CHECK (CANTIDAD_HABITACIONES_DISPONIBLES >= 0)
);




CREATE TABLE DA_HABITACION (
    ID_HABITACION      NUMBER       NOT NULL,
    NUMERO_HABITACION  VARCHAR2(20) NOT NULL,
    ID_HOTEL           NUMBER       NOT NULL,
    ID_TIPO_HABITACION NUMBER       NOT NULL,
    CONSTRAINT PK_DA_HABITACION PRIMARY KEY (ID_HABITACION),
    CONSTRAINT FK_DA_HAB_HOTEL
        FOREIGN KEY (ID_HOTEL) REFERENCES DA_HOTEL(ID_HOTEL),
    CONSTRAINT FK_DA_HAB_TIPO
        FOREIGN KEY (ID_TIPO_HABITACION) REFERENCES DA_TIPO_HABITACION(ID_TIPO_HABITACION)
);


CREATE TABLE DA_SERVICIO_COSTO_FIJO (
    ID_SERVICIO          NUMBER        NOT NULL,
    NOMBRE               VARCHAR2(100) NOT NULL,
    APLICA               VARCHAR2(50)  NOT NULL,
    TIPO_COSTO           VARCHAR2(50)  NOT NULL,
    TIPO_SERV_DISPONIBLE VARCHAR2(100) NOT NULL,
    DESCRIPCION_SERVICIO VARCHAR2(300) NOT NULL,
    PRECIO               NUMBER        NOT NULL,
    CONSTRAINT PK_DA_SCF PRIMARY KEY (ID_SERVICIO),
    CONSTRAINT CHK_DA_APLICA_SCF CHECK (
        APLICA IN ('Por reserva', 'Por noche', 'Por persona')
    ),
    CONSTRAINT CHK_DA_TCOSTO_SCF CHECK (TIPO_COSTO = 'Fijo'),
    CONSTRAINT CHK_DA_PRECIO_SCF CHECK (PRECIO > 0)
);


CREATE TABLE DA_SERVICIO_COSTO_CONSUMO (
    ID_SERVICIO          NUMBER        NOT NULL,
    NOMBRE               VARCHAR2(100) NOT NULL,
    APLICA               VARCHAR2(50)  NOT NULL,
    TIPO_COSTO           VARCHAR2(50)  NOT NULL,
    TIPO_SERV_DISPONIBLE VARCHAR2(100) NOT NULL,
    DESCRIPCION_SERVICIO VARCHAR2(300) NOT NULL,
    PRECIO_UNIDAD        NUMBER        NOT NULL,
    CONSTRAINT PK_DA_SCC PRIMARY KEY (ID_SERVICIO),
    CONSTRAINT CHK_DA_APLICA_SCC CHECK (
        APLICA IN ('Por reserva', 'Por noche', 'Por persona')
    ),
    CONSTRAINT CHK_DA_TCOSTO_SCC CHECK (TIPO_COSTO = 'Consumo'),
    CONSTRAINT CHK_DA_PRECIO_SCC CHECK (PRECIO_UNIDAD > 0)
);


CREATE TABLE DA_HOTEL_TIPO_HAB_SERVICIO (
    ID_HOTEL            NUMBER NOT NULL,
    ID_TIPO_HABITACION  NUMBER NOT NULL,
    ID_SERVICIO_FIJO    NUMBER,
    ID_SERVICIO_CONSUMO NUMBER,
    CONSTRAINT PK_DA_HTHS
        PRIMARY KEY (ID_HOTEL, ID_TIPO_HABITACION, ID_SERVICIO_FIJO, ID_SERVICIO_CONSUMO),
    CONSTRAINT FK_DA_HTHS_HOTEL
        FOREIGN KEY (ID_HOTEL) REFERENCES DA_HOTEL(ID_HOTEL),
    CONSTRAINT FK_DA_HTHS_TIPO
        FOREIGN KEY (ID_TIPO_HABITACION) REFERENCES DA_TIPO_HABITACION(ID_TIPO_HABITACION),
    CONSTRAINT FK_DA_HTHS_SCF
        FOREIGN KEY (ID_SERVICIO_FIJO) REFERENCES DA_SERVICIO_COSTO_FIJO(ID_SERVICIO),
    CONSTRAINT FK_DA_HTHS_SCC
        FOREIGN KEY (ID_SERVICIO_CONSUMO) REFERENCES DA_SERVICIO_COSTO_CONSUMO(ID_SERVICIO),
    CONSTRAINT CHK_DA_HTHS_SERV CHECK (
        ID_SERVICIO_FIJO IS NOT NULL OR ID_SERVICIO_CONSUMO IS NOT NULL
    )
);


CREATE TABLE DA_ADMINISTRADO_POR (
    ID_HOTEL            NUMBER NOT NULL,
    DOCUMENTO_IDENTIDAD NUMBER NOT NULL,
    CONSTRAINT PK_DA_ADMIN_POR
        PRIMARY KEY (ID_HOTEL, DOCUMENTO_IDENTIDAD),
    CONSTRAINT FK_DA_AP_HOTEL
        FOREIGN KEY (ID_HOTEL) REFERENCES DA_HOTEL(ID_HOTEL),
    CONSTRAINT FK_DA_AP_ADMIN
        FOREIGN KEY (DOCUMENTO_IDENTIDAD) REFERENCES DA_ADMINISTRADOR(DOCUMENTO_IDENTIDAD)
);


CREATE TABLE DA_RESERVAS (
    ID_RESERVA           NUMBER NOT NULL,
    FECHA_INICIO         DATE   NOT NULL,
    FECHA_FINAL          DATE   NOT NULL,
    PRECIO_TOTAL_RESERVA FLOAT  NOT NULL,
    ADULTOS              NUMBER NOT NULL,
    MENORES_3_ANIOS      NUMBER NOT NULL,
    ID_HOTEL             NUMBER NOT NULL,
    DOCUMENTO_IDENTIDAD  NUMBER NOT NULL,
    ID_TIPO_HABITACION   NUMBER NOT NULL,
    CONSTRAINT PK_DA_RESERVAS PRIMARY KEY (ID_RESERVA),
    CONSTRAINT FK_DA_RES_HOTEL
        FOREIGN KEY (ID_HOTEL) REFERENCES DA_HOTEL(ID_HOTEL),
    CONSTRAINT FK_DA_RES_CLIENTE
        FOREIGN KEY (DOCUMENTO_IDENTIDAD) REFERENCES DA_CLIENTE(DOCUMENTO_IDENTIDAD),
    CONSTRAINT FK_DA_RES_TIPO
        FOREIGN KEY (ID_TIPO_HABITACION) REFERENCES DA_TIPO_HABITACION(ID_TIPO_HABITACION),
    CONSTRAINT CHK_DA_FECHAS     CHECK (FECHA_FINAL > FECHA_INICIO),
    CONSTRAINT CHK_DA_ADULTOS    CHECK (ADULTOS >= 0),
    CONSTRAINT CHK_DA_MENORES    CHECK (MENORES_3_ANIOS >= 0),
    CONSTRAINT CHK_DA_PRECIO_RES CHECK (PRECIO_TOTAL_RESERVA > 0)
);



CREATE TABLE DA_RESERVA_SERVICIO (
    ID_RESERVA          NUMBER NOT NULL,
    ID_SERVICIO_FIJO    NUMBER,
    ID_SERVICIO_CONSUMO NUMBER,
    CANTIDAD            NUMBER,
    NOCHES              NUMBER,
    PERSONAS_SERVICIO   NUMBER NOT NULL,
    CONSTRAINT PK_DA_RS
        PRIMARY KEY (ID_RESERVA, ID_SERVICIO_FIJO, ID_SERVICIO_CONSUMO),
    CONSTRAINT FK_DA_RS_RESERVA
        FOREIGN KEY (ID_RESERVA) REFERENCES DA_RESERVAS(ID_RESERVA),
    CONSTRAINT FK_DA_RS_SCF
        FOREIGN KEY (ID_SERVICIO_FIJO) REFERENCES DA_SERVICIO_COSTO_FIJO(ID_SERVICIO),
    CONSTRAINT FK_DA_RS_SCC
        FOREIGN KEY (ID_SERVICIO_CONSUMO) REFERENCES DA_SERVICIO_COSTO_CONSUMO(ID_SERVICIO),
    CONSTRAINT CHK_DA_RS_SERV CHECK (
        ID_SERVICIO_FIJO IS NOT NULL OR ID_SERVICIO_CONSUMO IS NOT NULL
    )
);


SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME LIKE 'DA_%'
ORDER BY TABLE_NAME;
